apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "corp-blog.fullname" . }}-mysql
  labels:
    {{- include "corp-blog.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "corp-blog.fullname" . }}-mysql-headless
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      {{- include "corp-blog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "corp-blog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "corp-blog.fullname" . }}-mysql
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "corp-blog.fullname" . }}-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlUser | quote }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d/custom.cnf
              subPath: custom.cnf
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: {{ include "corp-blog.fullname" . }}-mysql-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        {{- end }}
