apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corp-blog.fullname" . }}-mysql
  labels:
    {{- include "corp-blog.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.mysqlPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corp-blog.fullname" . }}-wordpress
  labels:
    {{- include "corp-blog.labels" . | nindent 4 }}
type: Opaque
stringData:
  # WordPress читает WORDPRESS_DB_PASSWORD из env
  wordpress-db-password: {{ .Values.mysqlPassword | quote }}
